name: buildfork

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v5.0.5
        with:
          path: ~/.npm
          key: buildCache
      - run: nmp ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage
        uses: actions/upload-artifact@v7.0.1
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v7.0.1
        with:
          name: build
          path: build
